-- Sprint 0 / P0-2 (continued) — remove ID cards belonging to deleted accounts.
--
-- NO-OP MIGRATION. This originally ran `delete from storage.objects ...`
-- directly, but Supabase-hosted rejects that outright for every role,
-- including the migration role:
--
--   ERROR: Direct deletion from storage tables is not allowed.
--   Use the Storage API instead. (SQLSTATE 42501)
--
-- That's a platform-enforced rule, not a permissions gap this migration
-- could grant its way around — deleting the storage.objects row without
-- going through the Storage API leaves the backend blob orphaned, which is
-- exactly what Supabase blocks. No SQL migration can perform this delete.
--
-- The actual purge now lives in
-- scripts/purge-orphaned-student-id-cards.mjs, run manually against the
-- Storage API with the service_role key:
--
--   node --env-file=.env.local scripts/purge-orphaned-student-id-cards.mjs
--   node --env-file=.env.local scripts/purge-orphaned-student-id-cards.mjs --confirm
--
-- Finding this cleans up (docs/audit-2026-08-06.md §1 P0-2): storage.objects
-- held 25 rows in student-id-cards across 25 distinct owner uuids, while
-- public.profiles held 6 — 19 people who deleted their account still had
-- their ID document stored. Making the bucket private (20260806123000)
-- already ends the exposure; this purge goes further and removes the data,
-- since once the owning account is gone there is no verification left to
-- perform and therefore no lawful basis to keep an identity document.
--
-- This file is kept (as a no-op, not deleted) so the migration history
-- still records that this step was considered and why it moved out of the
-- SQL migration path, rather than silently vanishing from the timeline.
select 1;
